import { DIFFICULTY } from './util.js';

const README_HEADER = `# LeetCode Solutions

A collection of LeetCode solutions with detailed documentation.

[![LeetCode](https://img.shields.io/badge/LeetCode-000000?style=for-the-badge&logo=leetcode&logoColor=white)](https://leetcode.com)
[![GitHub stars](https://img.shields.io/github/stars/arunbhardwaj/LeetHub-2.0?style=for-the-badge)](https://github.com/arunbhardwaj/LeetHub-2.0)
[![GitHub forks](https://img.shields.io/github/forks/arunbhardwaj/LeetHub-2.0?style=for-the-badge)](https://github.com/arunbhardwaj/LeetHub-2.0)

---

## 📊 Stats

| Difficulty | Count |
|------------|-------|
| 🟢 Easy    | {easy} |
| 🟡 Medium  | {medium} |
| 🔴 Hard    | {hard} |
| **Total**  | **{total}** |

---

## 📚 Table of Contents

{tableOfContents}

---

## 🏷️ Topics

{topics}

---

*Generated by [LeetHub v2](https://github.com/arunbhardwaj/LeetHub-2.0)*
`;

const TABLE_HEADER = `| # | Problem | Difficulty | Solution |
|---|---------|------------|----------|
`;

const DIFFICULTY_BADGES = {
  [DIFFICULTY.EASY]: '🟢 Easy',
  [DIFFICULTY.MEDIUM]: '🟡 Medium',
  [DIFFICULTY.HARD]: '🔴 Hard',
  [DIFFICULTY.UNKNOWN]: '⚪ Unknown',
};

/**
 * Generates a comprehensive README.md with stats and table of contents
 * @param {Object} stats - Statistics object containing solved problems
 * @param {Object} shas - SHA objects containing problem data
 * @param {string} hook - Repository hook (owner/repo)
 * @returns {string} - Generated README content
 */
function generateReadme(stats, shas, hook) {
  const { easy = 0, medium = 0, hard = 0, solved = 0 } = stats || {};

  // Build table of contents
  let tableOfContents = TABLE_HEADER;
  const problemList = [];

  for (const problemName in shas) {
    if (shas.hasOwnProperty(problemName) && problemName !== 'README.md') {
      const problemData = shas[problemName];
      const difficulty = problemData.difficulty || 'unknown';
      const diffBadge = DIFFICULTY_BADGES[difficulty.toUpperCase()] || DIFFICULTY_BADGES[DIFFICULTY.UNKNOWN];

      // Extract problem number and name from slug (e.g., "0001-two-sum")
      const match = problemName.match(/^(\d+)-(.+)$/);
      if (match) {
        const [, num, name] = match;
        const displayName = name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
        problemList.push({
          num: parseInt(num),
          name: displayName,
          slug: problemName,
          difficulty: diffBadge,
          url: `https://leetcode.com/problems/${name}/`,
        });
      }
    }
  }

  // Sort by problem number
  problemList.sort((a, b) => a.num - b.num);

  // Build table rows
  for (const problem of problemList) {
    tableOfContents += `| ${problem.num} | [${problem.name}](${problem.url}) | ${problem.difficulty} | [Solution](./${problem.slug}) |\n`;
  }

  // Build topics section
  let topics = '';
  for (const problemName in shas) {
    if (shas.hasOwnProperty(problemName) && shas[problemName].topics) {
      const problemTopics = shas[problemName].topics;
      for (const topic of problemTopics) {
        if (!topics.includes(`## ${topic}`)) {
          topics += `### ${topic}\n\n`;
        }
      }
    }
  }

  // Replace placeholders
  let readme = README_HEADER
    .replace('{easy}', easy.toString())
    .replace('{medium}', medium.toString())
    .replace('{hard}', hard.toString())
    .replace('{total}', solved.toString())
    .replace('{tableOfContents}', tableOfContents)
    .replace('{topics}', topics || '_No topics yet_');

  return readme;
}

/**
 * Updates an existing README with new problem data
 * @param {string} existingReadme - Current README content
 * @param {Object} problemData - New problem data to add
 * @param {string} hook - Repository hook
 * @returns {string} - Updated README content
 */
function updateReadmeWithProblem(existingReadme, problemData, hook) {
  const { problemName, difficulty, topics } = problemData;

  // Extract problem number and name
  const match = problemName.match(/^(\d+)-(.+)$/);
  if (!match) return existingReadme;

  const [, num, name] = match;
  const displayName = name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  const diffBadge = DIFFICULTY_BADGES[difficulty?.toUpperCase()] || DIFFICULTY_BADGES[DIFFICULTY.UNKNOWN];

  // Check if problem already exists in table
  if (existingReadme.includes(`| ${num} |`)) {
    return existingReadme;
  }

  // Find the table and insert new row in sorted position
  const tableRegex = /\| # \| Problem \| Difficulty \| Solution \|[\s\S]*?(?=\n---|\n\n##|$)/;
  const tableMatch = existingReadme.match(tableRegex);

  if (tableMatch) {
    const table = tableMatch[0];
    const rows = table.split('\n').filter(row => row.startsWith('|') && !row.includes('---') && !row.includes('#'));

    // Parse existing rows
    const parsedRows = rows.map(row => {
      const parts = row.split('|').filter(p => p.trim());
      const numMatch = parts[0]?.trim().match(/^(\d+)$/);
      return numMatch ? { num: parseInt(numMatch[1]), row } : null;
    }).filter(Boolean);

    // Add new row
    const newRow = `| ${num} | [${displayName}](https://leetcode.com/problems/${name}/) | ${diffBadge} | [Solution](./${problemName}) |`;
    parsedRows.push({ num: parseInt(num), row: newRow });

    // Sort by number
    parsedRows.sort((a, b) => a.num - b.num);

    // Reconstruct table
    const newTable = `| # | Problem | Difficulty | Solution |\n|---|---------|------------|----------|\n${parsedRows.map(r => r.row).join('\n')}`;

    return existingReadme.replace(tableRegex, newTable);
  }

  return existingReadme;
}

export { generateReadme, updateReadmeWithProblem };
